name: Update Nightly rustc

on:
  schedule:
    - cron: "5 0 * * 6"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Update nightly rustc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-rbmt
        run: cargo install --git https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools.git --rev "$(cat rbmt-version)" cargo-rbmt

      - name: Update nightly toolchain pins
        run: |
          set -x
          eval "$(cargo rbmt toolchains --update-nightly)"
          echo "nightly_version=${RBMT_NIGHTLY}" >> $GITHUB_ENV
          if ! git diff --exit-code > /dev/null; then
              echo "changes_made=true" >> $GITHUB_ENV
          else
              echo "changes_made=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.changes_made == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          author: Update Nightly Rustc Bot <bot@example.com>
          committer: Update Nightly Rustc Bot <bot@example.com>
          title: Automated update to Cargo.toml nightly toolchain (to ${{ env.nightly_version }})
          body: |
            Automated update to Cargo.toml rbmt toolchain metadata.
          commit-message: Automated update to Cargo.toml nightly toolchain to ${{ env.nightly_version }}
          branch: create-pull-request/weekly-nightly-update
